-- Run this once in Supabase Dashboard → SQL Editor.
create table if not exists public.students (
  id bigint primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  family_code text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists students_teacher_id_idx on public.students(teacher_id);
create index if not exists students_parent_lookup_idx on public.students(lower(name), upper(family_code));
alter table public.students enable row level security;

drop policy if exists "Teachers read own students" on public.students;
create policy "Teachers read own students" on public.students for select to authenticated
using ((select auth.uid()) = teacher_id);

drop policy if exists "Teachers insert own students" on public.students;
create policy "Teachers insert own students" on public.students for insert to authenticated
with check ((select auth.uid()) = teacher_id);

drop policy if exists "Teachers update own students" on public.students;
create policy "Teachers update own students" on public.students for update to authenticated
using ((select auth.uid()) = teacher_id) with check ((select auth.uid()) = teacher_id);

drop policy if exists "Teachers delete own students" on public.students;
create policy "Teachers delete own students" on public.students for delete to authenticated
using ((select auth.uid()) = teacher_id);

create or replace function public.get_child_progress(p_student_name text, p_family_code text)
returns jsonb language sql stable security definer set search_path = public
as $$
  select payload from public.students
  where lower(name) = lower(trim(p_student_name))
    and upper(family_code) = upper(trim(p_family_code))
  limit 1;
$$;

revoke all on function public.get_child_progress(text,text) from public;
grant execute on function public.get_child_progress(text,text) to anon, authenticated;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'install_click', 'app_installed')),
  visitor_id text not null check (char_length(visitor_id) between 8 and 100),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_type_created_idx
  on public.analytics_events(event_type, created_at desc);
create index if not exists analytics_events_visitor_idx
  on public.analytics_events(visitor_id);

alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from anon, authenticated;
grant insert on public.analytics_events to anon, authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

drop policy if exists "Anonymous analytics inserts" on public.analytics_events;
create policy "Anonymous analytics inserts" on public.analytics_events
for insert to anon, authenticated
with check (event_type in ('page_view', 'install_click', 'app_installed'));

create or replace function public.get_site_analytics(p_pin text)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if p_pin <> '2468' then
    raise exception 'Invalid teacher PIN' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'total_visits', (select count(*) from public.analytics_events where event_type = 'page_view'),
    'unique_devices', (select count(distinct visitor_id) from public.analytics_events where event_type = 'page_view'),
    'install_clicks', (select count(*) from public.analytics_events where event_type = 'install_click'),
    'confirmed_installs', (select count(*) from public.analytics_events where event_type = 'app_installed'),
    'visits_today', (select count(*) from public.analytics_events where event_type = 'page_view' and created_at >= date_trunc('day', now())),
    'visits_7_days', (select count(*) from public.analytics_events where event_type = 'page_view' and created_at >= now() - interval '7 days')
  );
end;
$$;

revoke all on function public.get_site_analytics(text) from public;
grant execute on function public.get_site_analytics(text) to anon, authenticated;
