-- Run this once in Supabase Dashboard → SQL Editor.
create table if not exists public.students (
  id bigint primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  family_code text not null,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.students alter column teacher_id drop not null;

create index if not exists students_teacher_id_idx on public.students(teacher_id);
create index if not exists students_parent_lookup_idx on public.students(lower(name), upper(family_code));
alter table public.students enable row level security;

drop policy if exists "Teachers read own students" on public.students;
create policy "Teachers read own students" on public.students for select to authenticated
using ((select auth.uid()) = teacher_id);

drop policy if exists "Teachers insert own students" on public.students;
create policy "Teachers insert own students" on public.students for insert to authenticated
with check ((select auth.uid()) = teacher_id);

drop policy if exists "Teachers update own students" on public.students;
create policy "Teachers update own students" on public.students for update to authenticated
using ((select auth.uid()) = teacher_id) with check ((select auth.uid()) = teacher_id);

drop policy if exists "Teachers delete own students" on public.students;
create policy "Teachers delete own students" on public.students for delete to authenticated
using ((select auth.uid()) = teacher_id);

create or replace function public.get_child_progress(p_student_name text, p_family_code text)
returns jsonb language sql stable security definer set search_path = public
as $$
  select payload from public.students
  where lower(regexp_replace(trim(name), '\s+', ' ', 'g')) = lower(regexp_replace(trim(p_student_name), '\s+', ' ', 'g'))
    and upper(regexp_replace(translate(trim(family_code), '‐‑‒–—―−', '-------'), '\s+', '', 'g')) = upper(regexp_replace(translate(trim(p_family_code), '‐‑‒–—―−', '-------'), '\s+', '', 'g'))
  limit 1;
$$;

revoke all on function public.get_child_progress(text,text) from public;
grant execute on function public.get_child_progress(text,text) to anon, authenticated;

create or replace function public.publish_parent_students(p_teacher_pin text, p_records jsonb)
returns integer language plpgsql security definer set search_path = public
as $$
declare
  item jsonb;
  saved_count integer := 0;
  clean_code text;
  clean_name text;
  record_id bigint;
begin
  if p_teacher_pin <> '2468' then
    raise exception 'Invalid teacher PIN';
  end if;

  for item in select * from jsonb_array_elements(coalesce(p_records, '[]'::jsonb))
  loop
    clean_name := regexp_replace(trim(coalesce(item->>'name', '')), '\s+', ' ', 'g');
    clean_code := upper(regexp_replace(translate(trim(coalesce(item->>'familyCode', '')), '‐‑‒–—―−', '-------'), '\s+', '', 'g'));
    record_id := nullif(item->>'id', '')::bigint;

    if clean_name <> '' and clean_code <> '' and record_id is not null then
      insert into public.students (id, teacher_id, name, family_code, payload, updated_at)
      values (
        record_id,
        null,
        clean_name,
        clean_code,
        jsonb_set(jsonb_set(item, '{name}', to_jsonb(clean_name)), '{familyCode}', to_jsonb(clean_code)),
        now()
      )
      on conflict (id) do update set
        name = excluded.name,
        family_code = excluded.family_code,
        payload = excluded.payload,
        updated_at = now();
      saved_count := saved_count + 1;
    end if;
  end loop;

  return saved_count;
end;
$$;

revoke all on function public.publish_parent_students(text,jsonb) from public;
grant execute on function public.publish_parent_students(text,jsonb) to anon, authenticated;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('page_view', 'install_click', 'app_installed')),
  visitor_id text not null check (char_length(visitor_id) between 8 and 100),
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_type_created_idx
  on public.analytics_events(event_type, created_at desc);
create index if not exists analytics_events_visitor_idx
  on public.analytics_events(visitor_id);

alter table public.analytics_events enable row level security;
revoke all on public.analytics_events from anon, authenticated;
grant insert on public.analytics_events to anon, authenticated;
grant usage, select on sequence public.analytics_events_id_seq to anon, authenticated;

drop policy if exists "Anonymous analytics inserts" on public.analytics_events;
create policy "Anonymous analytics inserts" on public.analytics_events
for insert to anon, authenticated
with check (event_type in ('page_view', 'install_click', 'app_installed'));

drop function if exists public.get_site_analytics(text);

create or replace function public.get_site_analytics()
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Teacher authentication required' using errcode = '42501';
  end if;

  return jsonb_build_object(
    'total_visits', (select count(*) from public.analytics_events where event_type = 'page_view'),
    'unique_devices', (select count(distinct visitor_id) from public.analytics_events where event_type = 'page_view'),
    'install_clicks', (select count(*) from public.analytics_events where event_type = 'install_click'),
    'confirmed_installs', (select count(*) from public.analytics_events where event_type = 'app_installed'),
    'visits_today', (select count(*) from public.analytics_events where event_type = 'page_view' and created_at >= date_trunc('day', now())),
    'visits_7_days', (select count(*) from public.analytics_events where event_type = 'page_view' and created_at >= now() - interval '7 days')
  );
end;
$$;

revoke all on function public.get_site_analytics() from public;
grant execute on function public.get_site_analytics() to authenticated;
